#lang sicp

(define (element-of-set? x set)
  (cond ((null? set) false)
        ((= x (car set)) true)
        ((< x (car set)) false)
        (else (element-of-set? x (cdr set)))))


(define (intersection-set set1 set2)
  (if (or (null? set1) (null? set2))
      '()
      (let ((x1 (car set1)) (x2 (car set2)))
        (cond ((= x1 x2)
               (cons x1 (intersection-set (cdr set1)
                                          (cdr set2))))
              ((< x1 x2)
               (intersection-set (cdr set1) set2))
              ((< x2 x1)
               (intersection-set set1 (cdr set2)))))))

(define (adjoin-set x set)
  (cond ((null? set) (list x))
        ((<= x (car set)) (cons x set))
        (else (cons (car set) (adjoin-set x (cdr set))))))
;; (adjoin-set 1 (list 2 3))
;; (adjoin-set 2 (list 1 3))
;; (adjoin-set 3 (list 1 2))

;; basic principle: iterate through both sets, and stick the minimum car into a new set
(define (union-set set1 set2)
  (cond ((null? set1) set2)
        ((null? set2) set1)
        (else (let ((x1 (car set1))
                    (x2 (car set2)))
                (cond ((= x1 x2)
                       (cons x1 (union-set (cdr set1) (cdr set2))))
                      ((> x1 x2)
                       (cons x2 (union-set set1 (cdr set2))))
                      ((< x1 x2)
                       (cons x1 (union-set (cdr set1) set2))))))))
;; (union-set (list 1 3 5 7 9) (list 2 4 6))
;; (union-set (list 1 3 5 7) (list 2 4 6 8 10))
;; (union-set (list 1 2 3 4 5) (list 3 4 5 6 7))
;; (union-set '() (list 3 4 5 6 7))
;; (union-set (list 1 2 3 4 5) '())
